services:
  #Database
  provost_db:
    image: mariadb:11.3.2
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3324:3306
    restart: always
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: wordpress
    container_name: provost_db
  #Web
  provost_wp:
    depends_on:
      - provost_db
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 8088:80
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: provost_db
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_TABLE_PREFIX: wp_
    container_name: provost_wp
    volumes:
      - ./wp-content:/var/www/html/wp-content
  #PhpMyAdmin
  provost_myadmin:
    image: phpmyadmin:latest
    container_name: provost_myadmin
    restart: "no"
    ports:
      - 5008:80
    environment:
      PMA_HOST: provost_db
      UPLOAD_LIMIT: 100M
    depends_on:
      - provost_db
volumes:
  db_data:
  wp-content:
